SELECT [AddressID]
      ,[AddressLine1]
      -- ,[AddressLine2]
      ,[City]
      ,[StateProvinceID]
      ,[PostalCode]
      -- ,[SpatialLocation] 
      -- ,[rowguid]
      -- ,[ModifiedDate]
  FROM [AdventureWorks2019].[Person].[Address]
